org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=tacz_turrets
mod_name=TACZ Turrets
mod_license=MIT
mod_version=2.0.0
mod_group_id=com.entropy.tacz_turrets
mod_authors=Entropy159, jeducklet, voidfemme, SxilverKat
mod_description=Turrets for TACZ! Based off of TACZ Npcs!

geckolib_version=4.8.3
smartbrainlib_version=1.15
tacz_version=1.1.8-hotfix