modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = '''${description}'''
logoFile = "assets/tacz_turrets/icon.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "${loader_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "tacz"
mandatory = true
versionRange = "[${tacz},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${id}]]
modId = "smartbrainlib"
mandatory = true
versionRange = "[${smartbrainlib},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "geckolib"
mandatory = true
versionRange = "[${geckolib},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "ftbteams"
mandatory = false
versionRange = "[${ftbteams_min},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "openpartiesandclaims"
mandatory = false
versionRange = "[${opac_min},)"
ordering = "NONE"
side = "BOTH"
