loom.platform=neoforge

mod.mc_dep=[1.21.1,1.21.2)
mod.loader_range=[21.1.0,21.2)
mod.pack_format=34

deps.neoforge_loader=21.1.253
deps.tacz_slug=tacz-1.21.1
deps.tacz=1.1.8-hotfix-r6
deps.geckolib=4.9.3
deps.smartbrainlib=1.16.11
deps.ftbteams=2101.1.11
deps.ftbteams_min=2101.1.0
deps.opac=neoforge-1.21.1-0.31.6
deps.opac_min=0.23.2
